### PR TITLE
Implement Props to Hide Prev/Next Buttons

### PR DESCRIPTION
**Pull request by pburtchaell**
Please do not merge. 

There's still some more work to be done here and I haven't actually tested the code because I can't get the example to link to the package. Is the example working?

Changes:
- Adds `nextHidden` boolean prop to hide next button (defaults to `false`)
- Adds `prevHidden` boolean prop to hide prev button (also defaults to `false`)
- Renames `previousDisabled` prop to `prevDisabled` (to follow the rest of the props)

Connect https://github.com/ardaogulcan/react-native-keyboard-accessory/issues/5.

### CODE REVIEW

**Comment by pburtchaell** [comment]
Hello, do you have any status on this?

**Comment by ardaogulcan** [comment]
Hi @pburtchaell I've fixed the example. Can you rebase from master and try the example.

**Comment by pburtchaell** [comment]
Awesome! I'll do that either tomorrow or this weekend. 😄

**Comment by pburtchaell** [comment]
Thanks, I'm going to get to this today.

**Comment by pburtchaell** [comment]
OK @ardaogulcan, I've finished this up with a working example and made the changes you requested! This is ready for another review. 😄Let me know if you have any questions or if you want me to make any changes. Thanks! 🙌

**Comment by ardaogulcan** [comment]
Hi @pburtchaell thanks for the pr I have merged it and updated npm version to 0.0.6

**Pull request merged**
